# Generated by Django 3.0.5 on 2021-08-27 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pendingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('authToken', models.CharField(max_length=100)),
                ('joinAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='websiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('websitelogo', models.ImageField(upload_to='logo/website/')),
            ],
        ),
        migrations.CreateModel(
            name='memberWorking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workingPlace', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
                ('userName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='memberWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.websiteType')),
                ('userName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='memberPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('userName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='memberInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionName', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
                ('userName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='memberBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('memberProfilePhoto', models.ImageField(blank=True, null=True, upload_to='images/ProfilePhoto/')),
                ('memberCoverPhoto', models.ImageField(blank=True, null=True, upload_to='images/CoverPhoto/')),
                ('memberDivision', models.CharField(blank=True, max_length=50, null=True)),
                ('memberDistrict', models.CharField(blank=True, max_length=50, null=True)),
                ('memberBirthDate', models.DateField(blank=True, null=True)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
                ('joinAt', models.DateField(blank=True, null=True)),
                ('followedMember', models.ManyToManyField(related_name='Friends', to=settings.AUTH_USER_MODEL)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
