# Generated by Django 3.2.6 on 2021-08-29 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210828_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberworking',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='memberbasic',
            name='followedMember',
        ),
        migrations.DeleteModel(
            name='memberInstitution',
        ),
        migrations.DeleteModel(
            name='memberWorking',
        ),
    ]
