# Generated by Django 5.1 on 2026-02-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20210829_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberbasic',
            options={'verbose_name': 'Member Basic', 'verbose_name_plural': 'Member Basics'},
        ),
        migrations.AlterModelOptions(
            name='memberphonenumber',
            options={'verbose_name': 'Member Phone Number', 'verbose_name_plural': 'Member Phone Numbers'},
        ),
        migrations.AlterModelOptions(
            name='memberwebsite',
            options={'verbose_name': 'Member Website', 'verbose_name_plural': 'Member Websites'},
        ),
        migrations.AlterModelOptions(
            name='pendingaccount',
            options={'verbose_name': 'Pending Account', 'verbose_name_plural': 'Pending Accounts'},
        ),
        migrations.AlterModelOptions(
            name='websitetype',
            options={'verbose_name': 'Website Type', 'verbose_name_plural': 'Website Types'},
        ),
        migrations.AddField(
            model_name='memberbasic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='memberbasic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
