# Generated by Django 3.0.2 on 2020-09-16 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200502_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(default='', max_length=50)),
                ('car_description', models.TextField(default='', max_length=2000)),
                ('car_driverRate', models.IntegerField(default=0)),
                ('car_distanceRate', models.IntegerField(default=0)),
                ('car_hourRate', models.IntegerField(default=0)),
                ('car_deliveryRate', models.IntegerField(default=0)),
                ('car_capacity', models.IntegerField(default=0)),
                ('car_quantity', models.IntegerField(default=0)),
                ('car_image', models.ImageField(default='', upload_to='shop/images')),
                ('car_category', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
