# Generated by Django 3.0.2 on 2020-09-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200916_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_description',
        ),
    ]
