# Generated by Django 3.0.2 on 2020-09-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_car_car_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_distanceRate',
        ),
    ]
